//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTopicos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Articulos()
        {
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public string codigoArticulo { get; set; }
        public string nombre { get; set; }
        public System.DateTime fechaIngreso { get; set; }
        public string estado { get; set; }
        public string categoria { get; set; }
        public string subCategoria { get; set; }
        public Nullable<System.DateTime> fechaEntrega { get; set; }
        public string descripcion { get; set; }
    
        public virtual CategoriasArticulos CategoriasArticulos { get; set; }
        public virtual SubCategoriasArticulos SubCategoriasArticulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
