//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTopicos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroDePerdidas
    {
        public string codigoUsuario { get; set; }
        public string categoria { get; set; }
        public string subCategoria { get; set; }
        public string descripcion { get; set; }
    
        public virtual CategoriasArticulos CategoriasArticulos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual SubCategoriasArticulos SubCategoriasArticulos { get; set; }
    }
}
