//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTopicos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroDevoluciones1
    {
        public string codigoDevolucion { get; set; }
        public string codigoUsuario { get; set; }
        public string codigoArticulo { get; set; }
    
        public virtual Articulos Articulos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
